#!/usr/bin/env bash
color=1

run_command() {
    print_bar
    $@
    print_bar
}

print_bar() {
    width=$(tput cols)
    echo -n "$(tput setaf $color)"
    for i in $(seq 1 $width); do
	echo -n '='
    done
    echo "$(tput sgr0)"
}

if [ "$#" -lt 2 ]; then
    echo "USAGE: watchrun [directory] [command]"
    exit 1
fi

directory="$1"
shift
commmand="$@"

run_command $commmand
change=""
while :; do
    # Wait for something to change.
    echo "$(tput setaf $color)Watching...$(tput sgr0)"
    change=$("inotifywait --event close_write,moved_to,create --recursive --quiet --exclude \
        '(.*\.hg.*|.*\.git.*|.*\.svn.*|\.#.*|#.*#)' $directory")
    echo "$(tput setaf $color)$change$(tput sgr0)"
    echo "$(tput setaf $color)Triggered. Running command.$(tput sgr0)"
    run_command $commmand
    echo "$(tput setaf $color)Done.$(tput sgr0)"
done
